apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: example-ray-job-image
spec:
  lookupPolicy:
    local: false
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: res-cpe-team-docker-local.artifactory.swg-devops.com/cpe/tracker/example-ray-job
    referencePolicy:
      type: Source