apiVersion: cpe.cogadvisor.io/v1
kind: Benchmark
metadata:
  name: mpilat
  namespace: default
spec:
  benchmarkOperator:
    name: mpi
    namespace: default
  benchmarkSpec: |
    slotsPerWorker: 1
    cleanPodPolicy: Running
    mpiReplicaSpecs:
      Launcher:
        replicas: 1
        template:
          spec:
            containers:
            - image: res-cpe-team-docker-local.artifactory.swg-devops.com/osubenchmark:5.6.3
              name: mpi-bench-master
              command:
              - mpirun
              - --allow-run-as-root
              - -np
              - "2"
              - /osu-micro-benchmarks-5.6.3/mpi/pt2pt/osu_latency
              - -m
              - "4194304"
            imagePullSecrets:
            - name: res-cpe-team-docker-local
            nodeSelector:
              profile: openshift-default
      Worker:
        replicas: 2
        template:
          spec:
            affinity:
              podAntiAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                      - key: mpi_job_name
                        operator: In
                        values:
                        - osu-benchmark-bw
                    topologyKey: kubernetes.io/hostname
            containers:
            - image: res-cpe-team-docker-local.artifactory.swg-devops.com/osubenchmark:5.6.3
              name: mpi-bench-worker
            imagePullSecrets:
            - name: res-cpe-team-docker-local
            nodeSelector:
              profile: openshift-default
  repetition: 2
  iterationSpec:
    sequential: true
    minimize: true
    iterations:
      - name: maxsize
        location: ".mpiReplicaSpecs.Launcher.template.spec.containers[0].command[6]"
    nodeSelection:
      location: ".mpiReplicaSpecs.Worker.template.spec.nodeSelector"
      values:
      - "auto-tuned"
      selector:
        matchLabels:
          beta.kubernetes.io/instance-type: "bx2.4x16"
  parserKey: osu