apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpe-parser
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: parser
        env:
        - name: CPE_COS_LOG_APIKEY
          valueFrom:
            secretKeyRef:
              key: apiKey
              name: cpe-cos-key
        - name: CPE_COS_LOG_SERVICE_ID
          valueFrom:
            secretKeyRef:
              key: serviceInstanceID
              name: cpe-cos-key
        - name: CPE_COS_LOG_AUTH_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: authEndpoint
              name: cpe-cos-key
        - name: CPE_COS_LOG_SERVICE_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: serviceEndpoint
              name: cpe-cos-key
        - name: CPE_COS_LOG_RAW_BUCKET
          valueFrom:
            secretKeyRef:
              key: rawBucketName
              name: cpe-cos-key