apiVersion: cpe.cogadvisor.io/v1
kind: BenchmarkOperator
metadata:
  name: mpi
spec:
  apiVersion: kubeflow.org/v1alpha2
  kind: MPIJob
  adaptor: mpi
  crd:
    host: https://raw.githubusercontent.com/sunya-ch/mpi-operator/master
    paths:
    - /deploy/v1alpha2/crd.yaml
  deploySpec:
    namespace: mpi-operator
    yaml:
      host: https://raw.githubusercontent.com/sunya-ch/mpi-operator/master
      paths:
      - /deploy/v1alpha2/namespace.yaml
      - /deploy/v1alpha2/serviceaccount.yaml
      - /deploy/v1alpha2/cr.yaml
      - /deploy/v1alpha2/crb.yaml
      - /deploy/v1alpha2/deployment.yaml