apiVersion: cpe.cogadvisor.io/v1
kind: Benchmark
metadata:
  name: parsec
spec:
  benchmarkOperator:
    name: none
    namespace: default
  benchmarkSpec: |
    template:
      spec:
        containers:
        - name: parsec
          image: sunyanan/parsec:v3.0
          imagePullPolicy: Always
          command:
          - parsecmgmt 
          - -a
          - run
          - -p
          - {{ .package }} 
          - -i
          - {{ .input }}
        restartPolicy: Never
  parserKey: time
  repetition: 3
  interval: 30
  iterationSpec:
    iterations:
    - name: input
      values:
      - "native"
    - name: package
      values:
      - "bodytrack"
      - "canneal"
      - "raytrace"
      - "ferret"
    sequential: true
    minimize: true