apiVersion: cpe.cogadvisor.io/v1
kind: Benchmark
metadata:
  name: coremark
spec:
  benchmarkOperator:
    name: none
    namespace: default
  benchmarkSpec: |
    backoffLimit: 0
    template:
      spec:
        containers:
          - name: coremark
            image: {{ .image }}
            command:
            - sh
            - -c
            - ./coremark-{{ .thread }}thread{{if ne .thread "1"}}s{{end}}.exe
        restartPolicy: Never
  parserKey: coremark
  repetition: 3
  iterationSpec:
    iterations:
    - name: thread
      values:
      - "1"
      - "4"
      - "8"
      - "16"
      - "32"
    configurations:
    - name: image
      values:
      - "ghcr.io/sunya-ch/coremark:ubi"
    sequential: true