apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: extend-cluster-roleb-inding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: extend-cluster-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system