
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cpe.cogadvisor.io
  resources:
  - benchmarkoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cpe.cogadvisor.io
  resources:
  - benchmarkoperators/finalizers
  verbs:
  - update
- apiGroups:
  - cpe.cogadvisor.io
  resources:
  - benchmarkoperators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cpe.cogadvisor.io
  resources:
  - benchmarks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cpe.cogadvisor.io
  resources:
  - benchmarks/finalizers
  verbs:
  - update
- apiGroups:
  - cpe.cogadvisor.io
  resources:
  - benchmarks/status
  verbs:
  - get
  - patch
  - update
