apiVersion: cpe.cogadvisor.io/v1
kind: Benchmark
metadata:
  name: fio
  namespace: default
spec:
  benchmarkOperator:
    name: none
    namespace: default
  benchmarkSpec: |
    backoffLimit: 1
    template:
      spec:
        containers:
        - image: res-cpe-team-docker-local.artifactory.swg-devops.com/fio:3.24-ubi-8.3-x86_64
          name: runner 
          env:
          - name: RWMODE
            value: "read"
          - name: BS
            value: "4k"
          - name: THREADS
            value: "1"
          - name: FDIRECT
            value: "0"
          command:
          - sh
          - -c
          - 'fio -rw=${RWMODE} -bs=${BS} -numjobs=${THREADS} -filename=/tmp/test.out -ioengine=libaio -iodepth=8 -direct=${FDIRECT} -size=2G -runtime=100 -group_reporting -name=test'
        restartPolicy: Never
        imagePullSecrets:
        - name: res-cpe-team-docker-local
  parserKey: fio
  iterationSpec:
    iterations:
    - name: mode
      location: ".template.spec.containers[0].env[name=RWMODE].value"
      values:
      - "write"
      - "randread"
      - "randwrite"
    - name: bs
      location: ".template.spec.containers[0].env[name=BS].value"
      values:
      - "64k"
    - name: thread
      location: ".template.spec.containers[0].env[name=THREADS].value"
      values:
      - "4"
    - name: direct
      location: ".template.spec.containers[0].env[name=FDIRECT].value"
      values:
      - "1"
    sequential: true