apiVersion: cpe.cogadvisor.io/v1
kind: Benchmark
metadata:
  name: stressng
spec:
  benchmarkOperator:
    name: none
    namespace: default
  benchmarkSpec: |
    template:
      spec:
        containers:
        - name: stress
          image: alexeiled/stress-ng
          imagePullPolicy: IfNotPresent
          env:
          - name: TIMEOUT
            value: 60s
          - name: STRESSOR
          - name: STRESS_LOAD
          command:
          - /stress-ng
          - --$(STRESSOR)
          - $(STRESS_LOAD)
          - --timeout
          - $(TIMEOUT)
          - --metrics-brief
        restartPolicy: Never
    backoffLimit: 4
  parserKey: stress
  repetition: 1
  interval: 5
  iterationSpec:
    iterations:
    - name: stressor
      location: ".template.spec.containers[0].env[name=STRESSOR].value;.template.spec.containers[0].env[name=STRESS_LOAD].value"
      values:
      - "cpu;4"
      - "io;4"
      - "memcpy;4"
    sequential: true