apiVersion: v1
kind: Secret
metadata:
  name: thanos-objectstorage
type: Opaque
stringData:
  cos-config.yaml: |-
    type: S3
    config:
      bucket: ${BUCKET_NAME}
      endpoint: ${ENDPOINT}
      region: ${REGION}
      access_key: ${ACCESS_KEY}
      insecure: false
      signature_version2: false
      secret_key: ${SECRET_KEY}
      put_user_metadata: {}
      http_config:
        idle_conn_timeout: 0s
        response_header_timeout: 0s
        insecure_skip_verify: false
      trace:
        enable: false