apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-monitoring-view-adv
subjects:
- kind: ServiceAccount
  name: grafana-serviceaccount
  namespace: ${GRAFANA_NAMESPACE}
roleRef:
  kind: ClusterRole
  name: cluster-monitoring-view-adv
  apiGroup: rbac.authorization.k8s.io