apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: thanos-query
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        httpHeaderName1: Authorization
        timeInterval: 5s
        tlsSkipVerify: true
      name: thanos-query
      secureJsonData:
        httpHeaderValue1: 'Bearer ${BEARER_TOKEN}'
      type: prometheus
      url: 'http://thanos-query.cpe-monitoring-system.svc.cluster.local:9090'
  name: thanos-query.yaml