apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: cpe-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: BenchmarkOperator is the Schema for the benchmarkoperators API
      displayName: Benchmark Operator
      kind: BenchmarkOperator
      name: benchmarkoperators.cpe.cogadvisor.io
      version: v1
    - description: Benchmark is the Schema for the benchmarks API
      displayName: Benchmark
      kind: Benchmark
      name: benchmarks.cpe.cogadvisor.io
      version: v1
  description: CPE benchmarking, monitoring, and analyzing tool
  displayName: cpe
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - benchmark
  links:
  - name: Cpe Operator
    url: https://cpe-operator.domain
  maturity: alpha
  provider:
    name: IBM Research - Tokyo
  version: 0.0.0
