apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pushgateway
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: http
  selector:
    matchLabels:
      app: prometheus-pushgateway
