apiVersion: cpe.cogadvisor.io/v1
kind: Benchmark
metadata:
  name: cpe-benchmark-ext-sample
  namespace: ray-operator-system
spec:
  benchmarkOperator:
    name: ray
    namespace: default
  benchmarkSpec: |
    template:
      spec:
        restartPolicy: Never
        containers:
          - securityContext:
              privileged: true
            name: ray
            image: res-cpe-team-docker-local.artifactory.swg-devops.com/cpe/tracker/example-ray-job:latest
            command: [ "/bin/bash", "-c", "--" ]
            args:
              - "wget https://raw.githubusercontent.com/ray-project/ray/master/doc/kubernetes/example_scripts/job_example.py && echo $REVISION_TEST && python job_example.py"
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
            env:
            - name: OMP_NUM_THREADS
              value: "1"
            - name: MAX_SCALE
              value: "2"
        imagePullSecrets:
        - name: res-cpe-team-docker-local
  trackBuildConfigs:
  - kind: BuildConfig
    name: ray-example
    namespace: default
  iterationSpec:
    iterations:
    - name: maxscale
      location: ".template.spec.containers[0].env[name=MAX_SCALE].value"
      values:
      - "4"
      - "8"
  parserKey: default
  sidecar: false
  exportDst: 
  - prometheus
  - sysdig