kind: Service
apiVersion: v1
metadata:
  name: push-gateway
  namespace: cpe-monitoring-system
  labels:
    app: push-gateway
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9091
      targetPort: http
  selector:
    app: push-gateway
  type: ClusterIP
  sessionAffinity: None