resources:
- parser.yaml

# [LOG-COS] patch Cloud Object Storage setting
# patchesStrategicMerge:
# - patches/log_cos.yaml

images:
- name: parser
  newName: ghcr.io/ibm/cpe-operator/parser
  newTag: v1.0.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
