apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpe-parser
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpe-parser
  template:
    metadata:
      labels:
        app: cpe-parser
    spec:
      containers:
        - name: cpe-parser
          env:
          - name: CPE_COS_LOG_APIKEY
            valueFrom:
              secretKeyRef:
                key: apiKey
                name: cpe-cos-key
          - name: CPE_COS_LOG_SERVICE_ID
            valueFrom:
              secretKeyRef:
                key: serviceInstanceID
                name: cpe-cos-key
          - name: CPE_COS_LOG_AUTH_ENDPOINT
            valueFrom:
              secretKeyRef:
                key: authEndpoint
                name: cpe-cos-key
          - name: CPE_COS_LOG_SERVICE_ENDPOINT
            valueFrom:
              secretKeyRef:
                key: serviceEndpoint
                name: cpe-cos-key
          - name: CPE_COS_LOG_RAW_BUCKET
            valueFrom:
              secretKeyRef:
                key: rawBucketName
                name: cpe-cos-key
          - name: PUSHGATEWAY_URL
            value: http://pushgateway-prometheus-pushgateway.cpe-monitoring-system:9091
          image: res-cpe-team-docker-local.artifactory.swg-devops.com/cpe/parser:v0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
      - name: res-cpe-team-docker-local
---
apiVersion: v1
kind: Service
metadata:
  name: cpe-parser
spec:
  selector:
    app: cpe-parser
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080