apiVersion: cpe.cogadvisor.io/v1
kind: Benchmark
metadata:
  name: sysbench
  namespace: my-ripsaw
spec:
  benchmarkOperator:
    name: ripsaw
    namespace: default
  benchmarkSpec: |
    workload:
      name: sysbench
      args:
        enabled: true
        tests:
        - name: cpu
          parameters:
            cpu-max-prime: 2000
        - name: fileio
          parameters:
            file-test-mode: rndrw
  parserKey: sysbench
  iterationSpec:
    iterations:
    - name: maxprime
      location: .workload.args.tests[0].parameters.cpu-max-prime
      values:
      - "3000"
    sequential: true