apiVersion: cpe.cogadvisor.io/v1
kind: Benchmark
metadata:
  name: iperf3
  namespace: my-ripsaw
spec:
  benchmarkOperator:
    name: ripsaw
    namespace: default
  benchmarkSpec: |
    workload:
      name: iperf3
      args:
        pairs: 1
        hostnetwork: false
        pin: true
        pin_server: "10.248.0.55"
        pin_client: "10.248.0.58"
        port: 5201
        transmit_type: time
        transmit_value: 60
        omit_start: 0
        ip_tos: 0
        streams: 1
        extra_options_client: ' '
        extra_options_server: ' '
  parserKey: iperf3
  iterationSpec:
    configurations:
    - name: client
      location: ".workload.args.pin_client"
    - name: server
      location: ".workload.args.pin_server"
    sequential: true