apiVersion: cpe.cogadvisor.io/v1
kind: Benchmark
metadata:
  name: coremark-cx2-16x32
  namespace: default
spec:
  benchmarkOperator:
    name: none
    namespace: default
  benchmarkSpec: |
    backoffLimit: 0
    template:
      spec:
        imagePullSecrets:
        - name: res-cpe-team-docker-local
        containers:
          - name: coremark
            image: res-cpe-team-docker-local.artifactory.swg-devops.com/coremark:ubi
            env:
            - name: THREADNUM
              value: "4threads"
            command:
            - sh
            - -c
            - 'for i in `seq 1 10`; do ./coremark-${THREADNUM}.exe; done'
        restartPolicy: Never
        nodeSelector:
          profile: openshift-default
  parserKey: coremark
  interval: 30
  iterationSpec:
    iterations:
    - name: t
      location: ".template.spec.containers[0].env[name=THREADNUM].value"
    configurations:
    - name: image
      location: ".template.spec.containers[0].image"
    nodeSelection:
      location: ".template.spec.nodeSelector"
      values:
        - "auto-tuned"
      selector:
        matchLabels:
          beta.kubernetes.io/instance-type: "cx2.16x32"
    sequential: true