name: Build and push controller

on:
  push:
    branches:
      - main
      - v1.0.0
    paths:
      - .github/workflows/**
      - controllers/**
      - api/**
      - ./main.go
      - ./go.mod
      - config/**
      - ./Dockerfile
      - ./bundle.Dockerfile
      - ./Makefile

env:
  IMAGE_VERSION: '1.0.0'

jobs:    
  build-push-controller:
    if: ${{ github.repository_owner == 'IBM' }}
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/ibm/cpe-operator/controller
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.0'
      - name: Tidy
        run: |
          go mod tidy
          make generate fmt vet
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push controller
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:v${{ env.IMAGE_VERSION }}
          file: ./Dockerfile