name: Build and push parser

on:
  push:
    branches:
      - main
      - v1.0.0
    paths:
      - .github/workflows/**
      - cpe-parser/**

env:
  IMAGE_VERSION: '1.0.0'

jobs:    
  build-push-parser:
    if: ${{ github.repository_owner == 'IBM' }}
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/ibm/cpe-operator/parser
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.0'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push parser
        uses: docker/build-push-action@v2
        with:
          context: cpe-parser
          push: true
          platforms: linux/amd64,linux/arm64,linux/s390x
          tags: |
            ${{ env.IMAGE_NAME }}:v${{ env.IMAGE_VERSION }}
          file: ./cpe-parser/Dockerfile